const actions = {
    DEXAPICTURE_REQUEST: 'DEXAPICTURE_REQUEST',
    DEXAPICTURE_SUCCESS: 'DEXAPICTURE_SUCCESS',
    DEXAPICTURE_ERROR: 'DEXAPICTURE_ERROR',
    DEXAPICTURE_GET: () => ({
      type: actions.DEXAPICTURE_REQUEST
    })
  };
  export default actions;
  